CREATE TABLE `footer_content` (
	`id` int AUTO_INCREMENT NOT NULL,
	`logoUrl` text,
	`findUsLabelHe` varchar(64),
	`findUsLabelEn` varchar(64),
	`addressHe` varchar(255),
	`addressEn` varchar(255),
	`neighborhoodHe` varchar(255),
	`neighborhoodEn` varchar(255),
	`phone` varchar(32),
	`hoursLabelHe` varchar(64),
	`hoursLabelEn` varchar(64),
	`hoursDaysHe` varchar(128),
	`hoursDaysEn` varchar(128),
	`hoursTimeHe` varchar(64),
	`hoursTimeEn` varchar(64),
	`copyrightHe` varchar(255),
	`copyrightEn` varchar(255),
	`privacyLabelHe` varchar(128),
	`privacyLabelEn` varchar(128),
	`privacyUrl` varchar(512),
	`accessibilityLabelHe` varchar(128),
	`accessibilityLabelEn` varchar(128),
	`accessibilityUrl` varchar(512),
	`instagramUrl` varchar(512),
	`facebookUrl` varchar(512),
	`tiktokUrl` varchar(512),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `footer_content_id` PRIMARY KEY(`id`)
);
