CREATE TABLE `blog_posts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`slug` varchar(255) NOT NULL,
	`titleHe` varchar(512) NOT NULL,
	`titleEn` varchar(512) NOT NULL,
	`excerptHe` text,
	`excerptEn` text,
	`contentHe` text,
	`contentEn` text,
	`coverImageUrl` text,
	`authorHe` varchar(128),
	`authorEn` varchar(128),
	`seoTitleHe` varchar(255),
	`seoTitleEn` varchar(255),
	`seoDescriptionHe` text,
	`seoDescriptionEn` text,
	`seoKeywordsHe` text,
	`seoKeywordsEn` text,
	`ogImageUrl` text,
	`published` boolean NOT NULL DEFAULT false,
	`publishedAt` timestamp,
	`sortOrder` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `blog_posts_id` PRIMARY KEY(`id`),
	CONSTRAINT `blog_posts_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `seo_settings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`pageSlug` varchar(128) NOT NULL,
	`titleHe` varchar(255),
	`titleEn` varchar(255),
	`descriptionHe` text,
	`descriptionEn` text,
	`keywordsHe` text,
	`keywordsEn` text,
	`ogTitle` varchar(255),
	`ogDescription` text,
	`ogImageUrl` text,
	`canonicalUrl` text,
	`schemaJson` text,
	`robots` varchar(128) DEFAULT 'index, follow',
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `seo_settings_id` PRIMARY KEY(`id`),
	CONSTRAINT `seo_settings_pageSlug_unique` UNIQUE(`pageSlug`)
);
